### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by Dani1973** [malforge/mdk2#48]
When building I get "system cannot find the path specified" while the shown binary path is correct.
I tried setting the ouput and the binary path in the ini but that didn't help either.

Output from build :
```
Build started at 23:33...
1>------ Build started: Project: SE_Test, Configuration: Debug x64 ------
1>Found local ini file: C:\Users\pp_da\source\repos\SE_Test\SE_Test.mdk.local.ini
1>Found ini file: C:\Users\pp_da\source\repos\SE_Test\SE_Test.mdk.ini
1>Successfully determined the binary path of Space Engineers: c:\program files (x86)\steam\SteamApps\common\SpaceEngineers\Bin64
1>Loading Space Engineers assemblies from c:\program files (x86)\steam\SteamApps\common\SpaceEngineers\Bin64
1>The system cannot find the path specified.
1>C:\Users\pp_da\.nuget\packages\mal.mdk2.pbpackager\2.0.12\build\Mal.Mdk2.PbPackager.props(14,9): error MSB3073: The command ""C:\Users\pp_da\.nuget\packages\mal.mdk2.pbpackager\2.0.12\build\..\tools\mdk.exe" restore "C:\Users\pp_da\source\repos\SE_Test\SE_Test.csproj" -interactive" exited with code 3.
1>Done building project "SE_Test.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 23:33 and took 00,196 seconds ==========
```

**Comment by malware-dev** [comment]
Update your nuget packages and templates
https://github.com/malforge/mdk2/wiki

You're running an old broken version

**Comment by malware-dev** [comment]
(it's supposed to inform you there's a new version available but apparently that only works when it feels like it 😒

**Comment by FcoVega** [comment]
Hi, 

I'm not sure if it is not supposed to comment on closed issues but it is pretty similar to my problem but the exit code I have is -1.

I check the updates available, the only thing I did since creating the project from the template was to update the package Microsoft.IO.Redist from version 6.0.0 to 6.1.0 because of vulnerabilities.

I tried to run VS with admin rights but still the same issue. I'm running VS 17.12.0

I still have the old MDK/SE 1.5 installed, or that is what is shown in the about window.

Can you give a hint where should I look for the problem?

Build started at 11:11 PM...
1>------ Build started: Project: Mdk.SEMyFirstScript, Configuration: Debug x64 ------
1>Found local ini file: P:\SpaceEngineersScripts\Mdk.SEMyFirstScript\Mdk.SEMyFirstScript.mdk.local.ini
1>Found ini file: P:\SpaceEngineersScripts\Mdk.SEMyFirstScript\Mdk.SEMyFirstScript.mdk.ini
1>Successfully determined the binary path of Space Engineers: p:\programs\steam\SteamApps\common\SpaceEngineers\Bin64
1>Loading Space Engineers assemblies from p:\programs\steam\SteamApps\common\SpaceEngineers\Bin64
1>Only one project file can be specified.
1>C:\Users\FcoVe\.nuget\packages\mal.mdk2.pbpackager\2.0.14\build\Mal.Mdk2.PbPackager.props(14,9): error MSB3073: The command ""C:\Users\FcoVe\.nuget\packages\mal.mdk2.pbpackager\2.0.14\build\..\tools\mdk.exe" restore "P:\SpaceEngineersScripts\Mdk.SEMyFirstScript\Mdk.SEMyFirstScript.csproj" no" exited with code -1.
1>Done building project "Mdk.SEMyFirstScript.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 11:11 PM and took 00.986 seconds ==========

**Comment by malware-dev** [comment]
It will _always_ exit with the code -1 if something goes wrong. This is a new issue.

The last bits are from the dead MDK1, you can ignore that.

"1>Only one project file can be specified." Somehow it thinks you're trying to process more than one project in a single compilation, which is weird. Either way you'll have to make a new issue.
